apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
  namespace: marketplace
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DATABASE_URL: "jdbc:postgresql://marketplace-db.marketplace.svc.cluster.local:5432/marketplace-db"
  POSTGRES_USERNAME: "postgres"
  DB_NAME: "marketplace-db"

